# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_curiesr_wrappers", use_symbols = TRUE, package_name = "curiesr")

#' @docType package
#' @usage NULL
#' @useDynLib curiesr, .registration = TRUE
NULL

ConverterR <- new.env(parent = emptyenv())

ConverterR$new <- function() .Call(wrap__ConverterR__new)

ConverterR$compress <- function(uri) .Call(wrap__ConverterR__compress, self, uri)

ConverterR$expand <- function(curie) .Call(wrap__ConverterR__expand, self, curie)

#' @export
`$.ConverterR` <- function (self, name) { func <- ConverterR[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ConverterR` <- `$.ConverterR`


# nolint end
